server:
  port: 8081

spring:
  jpa:
    database-platform: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    data-username: postgres
    data-password: password
    url:

